library(Seurat)
library(tidyverse)
library(data.table)

# Set seed for reproducibility
set.seed(1)


# Source our own scRNA analysis utils functions
source("/project/cphg-millerlab/Jose/human_scRNA_meta_analysis/R_scripts/Utils/scRNA_processing_utils.R")

##################################################################################
# This script will plot gene expression specificity valuues using the ES matrix  #
# generated by CELLEX.                                                           #
##################################################################################

# Plot expression specificity for level1 annotations
level1_specificity = fread("/project/cphg-millerlab/Jose/human_scRNA_meta_analysis/rds_objects/integration_rds_objects/rPCA/alsaigh_pan_wirka_hu_int/CELLECT_inputs/whole_reference/CELLEX_files/rpca_int_sct_v3_level1_annotations_expression_specificity_gene_symbols_backup.esmu.csv")
head(level1_specificity)

# Define some well known markers for level1 annotations
level1_markers = c("MYH11", "PECAM1", "CD68", "NKG7", "C7", "MZB1", "LMOD1", "CD79A", "S100B", "PTGDS", "TPSAB1")
level1_df = level1_specificity[level1_specificity$gene %in% level1_markers,]

reshaped_level1_df = reshape2::melt(level1_df, id=c("gene"))
head(reshaped_level1_df)
names(reshaped_level1_df) = c("gene", "level1_annotation", "ESmu")

# Plot specificity results
reshaped_level1_df %>%
  ggplot(aes(x=level1_annotation, y=ESmu, fill=gene)) + 
  geom_col(position = "dodge", width=1) +
  ylab("Specificity (ESmu)") + 
  custom_theme() + 
  theme(aspect.ratio = 1.3,
        axis.text.x = element_text(angle=45, hjust=1)) +
  miller_discrete_scale(style = "bars", option = 2) 
  


###############################################
# Plot expression specificity for mural cells #
###############################################

# Load gene expression specificity matrix 
smc_peri_fibro_gene_exp = fread("/project/cphg-millerlab/Jose/human_scRNA_meta_analysis/rds_objects/integration_rds_objects/rPCA/alsaigh_pan_wirka_hu_int/CELLECT_inputs/LDSC_Peri_SMC_Fibro/CELLEX_files/smc_peri_fibro_prelim_annotations_expression_specificity_gene_symbols_backup.esmu.csv")
head(smc_peri_fibro_gene_exp)

# Inspect fibrochondro markers
smc_phenotypes = c("Contractile_SMC", "Fibromyocyte", "Fibrochondrocyte")
fibrochondro_markers = c("MYOCD", "CNN1", "MYH11", "ACTA2", "RUNX2", "SOX9", "IBSP", "TNFRSF11B", "CRTAC1", "LTBP1")
fibrochondro_markers_df = smc_peri_fibro_gene_exp[smc_peri_fibro_gene_exp$gene %in% fibrochondro_markers, ]
fibrochondro_markers_df_melt = melt(fibrochondro_markers_df)
fibrochondro_markers_df_melt$gene = factor(fibrochondro_markers_df_melt$gene, 
                                           levels = c("MYOCD", "CNN1", "MYH11", "ACTA2", "IBSP", "RUNX2", "SOX9", 
                                                      "TNFRSF11B", "CRTAC1", "LTBP1"))

fc_markers_specificity = fibrochondro_markers_df_melt %>% 
  filter(variable %in% smc_phenotypes) %>%
  ggplot(aes(x=variable, y=value, colour=gene)) +
  geom_jitter(size=4) + 
  xlab("SMC phenotype") + 
  ylab("ES") + 
  geom_vline(xintercept = c(3,5)) + 
  custom_theme + 
  #facet_wrap(~variable, scales = "free_y") + 
  theme(aspect.ratio = 1.7,
        legend.position = "right",
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_x_discrete(limits=c("Contractile_SMC", "Fibromyocyte", "Fibrochondrocyte")) + 
  npg_scale2

ggsave(file="/project/cphg-millerlab/Jose/human_scRNA_meta_analysis/manuscript_figures/Supplementary_Figure3/SuppFig3d_osteochondro_markers_ES.pdf",
       plot = fc_markers_specificity, width = 5, height = 7)
